--- Makefile    2025-08-12 14:06:00.000000000 +0100
+++ Makefile    2025-08-12 14:07:30.000000000 +0100
@@ -14,7 +14,8 @@
 # Use a separate variable for services that don't have an associated timer.
-ADDITIONAL_SERVICES := $(patsubst %,$(SYSTEMD_UNIT_DIR)/%, discord-startup.service)
+ADDITIONAL_SERVICES := $(patsubst %,$(SYSTEMD_UNIT_DIR)/%, discord-startup@.service)

@@ -42,6 +43,9 @@
 echo "Reloading systemd daemon..."
 sudo systemctl daemon-reexec
+echo "Enabling discord-startup@$(USER).service..."
+sudo systemctl enable discord-startup@$(USER).service
+sudo systemctl start discord-startup@$(USER).service
 echo "Enabling and starting timers and services..."
 $(foreach unit, $(notdir $(ALL_SERVICES) $(ALL_TIMERS)), sudo systemctl enable --now $(unit);)
 echo "Systemd installation finished."

